name: docker-image

on:
    pull_request:

jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
          go-version-file: 'server/go.mod'
        id: go

      - name: Get dependencies
        run: cd server && go mod download

      - name: Run tests
        run: cd server && go test -v ./...